name: React App – Run Automated Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install and test
        run: |
          npm ci
          npm test

